const CardActionTypes = {
    TOGGLE_CARD_HIDDEN: 'TOGGLE_CARD_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    REMOVE_ITEM:'REMOVE_ITEM',
    DECREASE_ITEM_QUANTITIES_BY_ONE:'DECREASE_ITEM_QUANTITIES_BY_ONE'
}

export default CardActionTypes;